import { useMemo } from 'react'
import { cathSvg, type CathOptions } from '../../shared/cath/cath'

// React wrapper for the shared Cath art (VISION.md "Cath: character bible"). The markup is generated by
// our own pure function from fixed art, never from user input, so injecting it is safe.
export default function CathArt({ className, ...options }: CathOptions & { className?: string }) {
  const html = useMemo(
    () => cathSvg(options),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [options.expression, options.outfit, options.framing, options.title, options.width, options.height, options.animate],
  )
  return <span className={`cath-art${className ? ` ${className}` : ''}`} dangerouslySetInnerHTML={{ __html: html }} />
}
