// Hedgerow's levels. H1 ships the first three of act 1, Brindle Hills (docs/design/hedgerow.md). Story
// follows SPEC 3.2's voice: short, specific, dry, warm. Later acts append to LEVELS.

import type { Level, WaveGroup } from "./engine";

const van = (count: number, gap: number, delay = 0): WaveGroup => ({
  enemy: "van",
  count,
  gap,
  delay,
});
const boss = (delay = 0): WaveGroup => ({
  enemy: "boss",
  count: 1,
  gap: 1,
  delay,
});
const drone = (count: number, gap: number, delay = 0): WaveGroup => ({
  enemy: "drone",
  count,
  gap,
  delay,
});
const truck = (count: number, gap: number, delay = 0): WaveGroup => ({
  enemy: "truck",
  count,
  gap,
  delay,
});
const influencer = (count: number, gap: number, delay = 0): WaveGroup => ({
  enemy: "influencer",
  count,
  gap,
  delay,
});
const blimp = (delay = 0): WaveGroup => ({
  enemy: "blimp",
  count: 1,
  gap: 1,
  delay,
});
const bulldozer = (count: number, gap: number, delay = 0): WaveGroup => ({
  enemy: "bulldozer",
  count,
  gap,
  delay,
});
const megadozer = (delay = 0): WaveGroup => ({
  enemy: "megadozer",
  count: 1,
  gap: 1,
  delay,
});
const phantom = (count: number, gap: number, delay = 0): WaveGroup => ({
  enemy: "phantom",
  count,
  gap,
  delay,
});
const clinic = (delay = 0): WaveGroup => ({
  enemy: "clinic",
  count: 1,
  gap: 1,
  delay,
});
const tender = (count: number, gap: number, delay = 0): WaveGroup => ({
  enemy: "tender",
  count,
  gap,
  delay,
});
const ship = (delay = 0): WaveGroup => ({
  enemy: "ship",
  count: 1,
  gap: 1,
  delay,
});
const convoy = (delay = 0): WaveGroup => ({
  enemy: "convoy",
  count: 1,
  gap: 1,
  delay,
});

/** A steady climb of `n` waves: vans, drones and (from wave `truckFrom`) trucks, growing a little each time. */
function ramp(
  n: number,
  o: {
    v: number;
    d: number;
    t?: number;
    truckFrom?: number;
    vs?: number;
    ds?: number;
    i?: number;
    infFrom?: number;
    b?: number;
    bFrom?: number;
    p?: number;
    pFrom?: number;
    e?: number;
    eFrom?: number;
  },
): WaveGroup[][] {
  return Array.from({ length: n }, (_, i) => {
    const groups = [
      van(Math.round(o.v + i * (o.vs ?? 1.2)), Math.max(0.9, 1.9 - i * 0.1)),
    ];
    groups.push(
      drone(
        Math.round(o.d + i * (o.ds ?? 1.4)),
        Math.max(0.5, 0.95 - i * 0.05),
        2,
      ),
    );
    if (o.t && i >= (o.truckFrom ?? 2))
      groups.push(
        truck(Math.round(o.t + (i - (o.truckFrom ?? 2)) * 0.8), 2.2, 4),
      );
    if (o.i && i >= (o.infFrom ?? 1))
      groups.push(
        influencer(Math.round(o.i + (i - (o.infFrom ?? 1)) * 0.5), 2.6, 3),
      );
    if (o.b && i >= (o.bFrom ?? 1))
      groups.push(
        bulldozer(Math.round(o.b + (i - (o.bFrom ?? 1)) * 0.6), 3, 5),
      );
    if (o.p && i >= (o.pFrom ?? 1))
      groups.push(
        phantom(Math.round(o.p + (i - (o.pFrom ?? 1)) * 0.5), 2.4, 6),
      );
    if (o.e && i >= (o.eFrom ?? 1))
      groups.push(tender(Math.round(o.e + (i - (o.eFrom ?? 1)) * 0.5), 2.8, 7));
    return groups;
  });
}

export const LEVELS: Level[] = [
  {
    id: 1,
    name: "Mara's Field",
    place: "Brindle Hills",
    cols: 6,
    rows: 7,
    path: [
      [0, 1],
      [4, 1],
      [4, 3],
      [1, 3],
      [1, 5],
      [5, 5],
    ],
    startMarks: 210,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow"],
    waves: [
      [van(3, 3)],
      [van(4, 2.6)],
      [van(4, 2.4), drone(2, 1.5, 6)],
      [van(5, 2.2), drone(3, 1.4, 5)],
      [van(6, 2), drone(4, 1.2, 4)],
    ],
    before: [
      {
        who: "narrator",
        text: "Brindle Hills, a Tuesday. Mara is halfway through a cheese sandwich when something hums overhead.",
      },
      {
        who: "mara",
        text: "There's a drone in my beans, Cath. It's taking photographs. Of my beans.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Then it's a survey. First the photographs, then the offer, then the bulldozer. I've seen the order.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Good news: you've got a hedge, a scarecrow and me. Let's put them where the lane bends.",
      },
    ],
    after: [
      {
        who: "mara",
        text: "Well. That's the first van I've ever seen turn round on its own.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "It won't be the last one that comes. But now they know what your beans are made of.",
      },
    ],
    reward:
      'Lore card: "Mara\'s ledger", forty years of bean prices, all of them fair.',
  },
  {
    id: 2,
    name: "The Long Lane",
    place: "Brindle Hills",
    cols: 6,
    rows: 8,
    path: [
      [5, 0],
      [1, 0],
      [1, 2],
      [4, 2],
      [4, 4],
      [0, 4],
      [0, 6],
      [5, 6],
    ],
    startMarks: 190,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow"],
    waves: [
      [van(4, 2.8)],
      [drone(4, 1.4), van(2, 2.6, 3)],
      [van(5, 2.2), drone(3, 1.2, 4)],
      [van(4, 2), drone(6, 1.1, 3)],
      [van(6, 1.9), drone(5, 1.1, 4)],
      [van(7, 1.7), drone(6, 1, 3)],
    ],
    before: [
      {
        who: "narrator",
        text: "Word travels fast in Brindle Hills. By breakfast, four farms know about the drone.",
      },
      {
        who: "bea",
        expression: "delighted",
        text: "I drew the van! It has a smiley face on it. Why do the mean ones always have smiley faces?",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "Because a frown wouldn't test well with customers, sweetheart.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "They're coming down the long lane this time. Plenty of room for hedges. Bea, you keep score.",
      },
    ],
    after: [
      {
        who: "bea",
        expression: "delighted",
        text: "Twenty-seven vans! I counted. Can I draw a medal for the hedge?",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Draw one for everyone. Hedges first.",
      },
    ],
    reward:
      'Scarecrow skin: "Bea\'s Sunday best", a hat and a very small bow tie.',
  },
  {
    id: 3,
    name: "The Acquisition Van",
    place: "Brindle Hills",
    cols: 6,
    rows: 8,
    path: [
      [0, 1],
      [5, 1],
      [5, 3],
      [0, 3],
      [0, 5],
      [5, 5],
    ],
    startMarks: 260,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow"],
    waves: [
      [van(5, 2.4)],
      [drone(6, 1.2), van(3, 2.4, 2)],
      [van(6, 2), drone(5, 1.1, 3)],
      [van(7, 1.8), drone(6, 1, 3)],
      [van(8, 1.6), drone(7, 0.9, 2)],
      [van(9, 1.5), drone(8, 0.9, 2)],
      [van(11, 1.3), drone(9, 0.8, 2)],
    ],
    before: [
      {
        who: "narrator",
        text: "A very clean white van parks at the edge of the hills. Nobody sees anyone get out. That is the alarming part.",
      },
      {
        who: "tomas",
        text: "It's an acquisition van. There's an offer letter on every windscreen in the valley. Nice paper, too.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Everything they send is in the same font. That's how you know it's one company with two names.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Right. Vans first, drones after, and nobody sells a thing today.",
      },
    ],
    after: [
      {
        who: "tomas",
        text: "They've stopped. Do you think that's the end of it?",
      },
      {
        who: "cath",
        expression: "worried",
        text: "No. They've gone to get a bigger van.",
      },
    ],
    reward:
      'Lore card: "The offer letter", 400 words that never once say the word "no".',
  },
  {
    id: 4,
    name: "Bea's Beehive",
    place: "Brindle Hills",
    cols: 6,
    rows: 8,
    path: [
      [0, 0],
      [3, 0],
      [3, 2],
      [0, 2],
      [0, 4],
      [4, 4],
      [4, 6],
      [1, 6],
      [1, 7],
      [5, 7],
    ],
    startMarks: 280,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive"],
    waves: [
      [van(5, 2.2)],
      [drone(6, 1.1), van(4, 2.2, 2)],
      [van(7, 1.9), drone(5, 1.1, 3)],
      [van(8, 1.7), drone(6, 1, 3)],
      [van(9, 1.5), drone(8, 0.9, 2)],
      [van(10, 1.4), drone(9, 0.8, 2)],
    ],
    before: [
      {
        who: "narrator",
        text: "Bea has been keeping bees behind the barn for a fortnight. Nobody was told. The bees weren't told either.",
      },
      {
        who: "bea",
        expression: "delighted",
        text: "They like the vans! They follow them! Is that bad?",
      },
      {
        who: "cath",
        expression: "wink",
        text: "It is the best thing that's happened all week. Bea, we're going to need a lot more hives.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "New tool: the Beehive. It stings everything near its target, so put it where the queue bunches up.",
      },
    ],
    after: [
      {
        who: "bea",
        expression: "delighted",
        text: "I named them all. This one is Gerald.",
      },
      { who: "cath", expression: "smirk", text: "Gerald did wonderful work." },
    ],
    reward:
      'Unlocked: the Beehive (sting a whole queue at once). Lore card: "Gerald".',
  },
  {
    id: 5,
    name: "Price War",
    place: "Brindle Hills",
    cols: 6,
    rows: 8,
    path: [
      [5, 0],
      [5, 2],
      [0, 2],
      [0, 4],
      [5, 4],
      [5, 6],
      [0, 6],
      [0, 7],
      [5, 7],
    ],
    startMarks: 300,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive"],
    waves: [
      [drone(8, 0.9)],
      [van(6, 1.8), drone(6, 1, 2)],
      [drone(10, 0.7), van(6, 1.7, 3)],
      [van(9, 1.5), drone(9, 0.8, 2)],
      [drone(14, 0.6), van(8, 1.5, 3)],
      [van(11, 1.3), drone(12, 0.7, 2)],
      [van(12, 1.2), drone(16, 0.55, 2)],
    ],
    before: [
      {
        who: "tomas",
        text: "They've cut every price in the valley by half. Even the eggs. Who sells eggs at half price? Nobody. It's a trap.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "It's a price war. They lose money until you close, then the prices come back up, with interest.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "Everyone will want the cheap eggs. Our job is to make the cheap eggs hard to get to.",
      },
    ],
    after: [
      {
        who: "tomas",
        text: "Well. I'm keeping my prices. Slightly higher than theirs. Slightly better eggs.",
      },
      {
        who: "cath",
        expression: "delighted",
        text: "That's the whole business plan, Tomas. Put it on a sign.",
      },
    ],
    reward:
      'Lore card: "Tomas\'s egg sign", hand-painted, very slightly crooked.',
  },
  {
    id: 6,
    name: "The Long Weekend",
    place: "Brindle Hills",
    cols: 6,
    rows: 8,
    path: [
      [0, 0],
      [5, 0],
      [5, 2],
      [1, 2],
      [1, 4],
      [4, 4],
      [4, 6],
      [0, 6],
      [0, 7],
      [5, 7],
    ],
    startMarks: 320,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive"],
    waves: [
      [van(6, 2)],
      [van(6, 1.8), drone(8, 0.9, 2)],
      [van(9, 1.5), drone(8, 0.8, 2)],
      [van(10, 1.4), drone(10, 0.75, 2)],
      [van(12, 1.2), drone(10, 0.7, 2)],
      [van(13, 1.1), drone(12, 0.65, 2)],
      [van(15, 1), drone(14, 0.6, 2)],
      [van(16, 0.95), drone(16, 0.55, 2)],
    ],
    before: [
      {
        who: "narrator",
        text: "Saturday. The corporations do not believe in weekends, only in overtime.",
      },
      {
        who: "mara",
        text: "Forty vans, Cath. I counted them. They're coming in shifts.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "That's the biggest push yet. They've stopped sending letters and started sending people.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "But we have a lane, a hedge and Gerald. I like our odds.",
      },
    ],
    after: [
      { who: "mara", text: "Sunday tea, then?" },
      {
        who: "cath",
        expression: "smirk",
        text: "Sunday tea. And someone go and check on the acquisition van. It's been very quiet over there.",
      },
    ],
    reward:
      'Lore card: "Shift rota", a list of vans with a very tired-looking note at the bottom.',
  },
  {
    id: 7,
    name: "Crooked Fences",
    place: "Brindle Hills",
    cols: 6,
    rows: 8,
    path: [
      [0, 7],
      [0, 5],
      [3, 5],
      [3, 3],
      [0, 3],
      [0, 1],
      [5, 1],
      [5, 7],
    ],
    startMarks: 400,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive"],
    waves: [
      [van(7, 1.8)],
      [van(8, 1.6), drone(8, 0.8, 2)],
      [van(10, 1.4), drone(10, 0.7, 2)],
      [van(11, 1.3), drone(12, 0.65, 2)],
      [van(13, 1.2), drone(12, 0.6, 2)],
      [van(14, 1.1), drone(14, 0.55, 2)],
    ],
    before: [
      {
        who: "narrator",
        text: "Overnight, someone moves Mara's fence posts four feet to the left. It is technically legal. That is the worst part.",
      },
      {
        who: "mara",
        text: "Their surveyor says my field is smaller than I thought. My field has been this size since 1974.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Then we hold every inch of it, including the inches they've decided don't exist.",
      },
    ],
    after: [
      {
        who: "mara",
        text: "I moved the fence back. It is now six inches further left than it was. I win.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "That's the spirit. Slightly petty and completely correct.",
      },
    ],
    reward: 'Lore card: "Mara\'s tape measure", 30 metres of proof.',
  },
  {
    id: 8,
    name: "The Survey",
    place: "Brindle Hills",
    cols: 6,
    rows: 8,
    path: [
      [0, 0],
      [2, 0],
      [2, 2],
      [5, 2],
      [5, 4],
      [2, 4],
      [2, 6],
      [5, 6],
      [5, 7],
    ],
    startMarks: 440,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive"],
    waves: [
      [drone(10, 0.8)],
      [van(8, 1.6), drone(10, 0.7, 2)],
      [van(10, 1.4), drone(12, 0.65, 2)],
      [drone(18, 0.5), van(9, 1.4, 3)],
      [van(13, 1.2), drone(14, 0.6, 2)],
      [van(15, 1.1), drone(16, 0.55, 2)],
      [van(16, 1), drone(18, 0.5, 2)],
    ],
    before: [
      {
        who: "narrator",
        text: 'Forty drones, one clipboard. A young man in a hi-vis vest stands at the gate and says he is "just here to measure".',
      },
      {
        who: "bea",
        expression: "worried",
        text: "He's measuring the beehives. Why is he measuring the beehives?",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Because a hive is worth money, sweetheart. And they'd like to own it.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "Nobody owns Gerald. Gerald is a free bee.",
      },
    ],
    after: [
      {
        who: "bea",
        expression: "delighted",
        text: "The man in the vest fell in the pond. Was that us?",
      },
      { who: "cath", expression: "wink", text: "Officially, no." },
    ],
    reward:
      'Lore card: "The clipboard", left behind, with one very honest line: "Nobody seems to mind."',
  },
  {
    id: 9,
    name: "Night Shift",
    place: "Brindle Hills",
    cols: 6,
    rows: 8,
    path: [
      [5, 0],
      [0, 0],
      [0, 2],
      [4, 2],
      [4, 4],
      [1, 4],
      [1, 6],
      [5, 6],
      [5, 7],
    ],
    startMarks: 460,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive"],
    waves: [
      [van(8, 1.5)],
      [van(9, 1.4), drone(12, 0.65, 2)],
      [van(12, 1.2), drone(12, 0.6, 2)],
      [van(13, 1.1), drone(15, 0.55, 2)],
      [van(15, 1), drone(16, 0.5, 2)],
      [van(17, 0.95), drone(18, 0.5, 2)],
      [van(18, 0.9), drone(20, 0.45, 2)],
    ],
    before: [
      {
        who: "narrator",
        text: "At two in the morning the vans come with their lights off. The drones do not have lights to turn off, which is somehow worse.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "They've stopped pretending it's polite. That means they know the acquisition van is nearly ready.",
      },
      { who: "tomas", text: "Should I make tea?" },
      {
        who: "cath",
        expression: "smirk",
        text: "Make a lot of tea, Tomas. It is going to be that kind of night.",
      },
    ],
    after: [
      { who: "tomas", text: "The tea was excellent. The vans were not." },
      {
        who: "cath",
        expression: "worried",
        text: "Something big is coming up the road. I can feel it in the fence posts.",
      },
    ],
    reward: 'Lore card: "Tomas\'s flask", still warm.',
  },
  {
    id: 10,
    name: "The Acquisition",
    place: "Brindle Hills",
    cols: 6,
    rows: 8,
    path: [
      [0, 0],
      [5, 0],
      [5, 2],
      [0, 2],
      [0, 4],
      [5, 4],
      [5, 6],
      [0, 6],
      [0, 7],
      [5, 7],
    ],
    startMarks: 380,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive"],
    waves: [
      [van(8, 1.5)],
      [van(10, 1.3), drone(12, 0.6, 2)],
      [van(12, 1.2), drone(14, 0.55, 2)],
      [van(14, 1.1), drone(16, 0.5, 2)],
      [van(16, 1), drone(18, 0.5, 2)],
      [boss(0), van(12, 1.2, 6), drone(16, 0.55, 8)],
    ],
    before: [
      {
        who: "narrator",
        text: 'The Acquisition Van is the size of a barn. It has a slogan on the side: "WE\'RE HERE FOR YOU." It has a smile, too. Nobody asked for the smile.',
      },
      {
        who: "mara",
        text: "Cath, that isn't a van. That's a lawyer with wheels.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "It's what they send when they've run out of letters. It's slow, it's enormous and it's utterly convinced it's already won.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Every hedge, every scarecrow, every hive, Gerald included. Let's show it what Brindle Hills thinks of an offer.",
      },
    ],
    after: [
      {
        who: "narrator",
        text: "The Acquisition Van sits in the lane, stopped. A single, very small turnip rolls off its roof.",
      },
      {
        who: "mara",
        text: "Forty years I've farmed this valley. I never thought I'd see the day a van gave up.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "It didn't give up, Mara. It went to get advice. Highmoor is next, and their advice comes with a price tag.",
      },
    ],
    reward:
      'Act 1 complete. Lore card: "The Van\'s manifesto", 90 pages, not one of them about farming.',
  },
  {
    id: 11,
    name: "Highmoor Market",
    place: "Highmoor",
    cols: 6,
    rows: 8,
    path: [
      [0, 1],
      [4, 1],
      [4, 3],
      [1, 3],
      [1, 5],
      [5, 5],
      [5, 7],
    ],
    startMarks: 420,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive"],
    waves: ramp(6, { v: 5, d: 6, vs: 1, ds: 1 }),
    before: [
      {
        who: "narrator",
        text: 'Highmoor sits on a cold hill above the clouds, and every Saturday its market fills the square. This Saturday, a banner says: "GRAND REOPENING, FEATURING PRICES."',
      },
      {
        who: "tomas",
        text: "They've rented every stall. Every one. The rent is a pound. Nobody in Highmoor has been charged a pound for anything in forty years, and it's terrifying.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "A pound this month, a hundred next. Come on, Tomas. We hold the road up to the square.",
      },
    ],
    after: [
      {
        who: "tomas",
        text: "The square is still ours. Nobody is quite sure what to do with the stall that was rented for a pound.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "Keep the receipt. It's evidence.",
      },
    ],
    reward:
      'Lore card: "The one-pound lease", signed in a pen that runs out halfway through the small print.',
  },
  {
    id: 12,
    name: "Cheap Eggs",
    place: "Highmoor",
    cols: 6,
    rows: 8,
    path: [
      [5, 0],
      [1, 0],
      [1, 2],
      [5, 2],
      [5, 4],
      [0, 4],
      [0, 6],
      [4, 6],
      [4, 7],
    ],
    startMarks: 440,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive"],
    waves: ramp(7, { v: 8, d: 9 }),
    before: [
      {
        who: "narrator",
        text: "A new stall opens at the top of the square. It sells eggs at a loss so vast that an accountant across the valley faints.",
      },
      {
        who: "tomas",
        text: "Half the town is queuing. Cath, they're my eggs. They just don't have my name on them any more.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "That's the trick. Take the name, keep the egg, add a barcode.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Let's remind Highmoor who kept the hens.",
      },
    ],
    after: [
      {
        who: "tomas",
        text: "Three people came back to my stall today. One brought a cake.",
      },
      {
        who: "cath",
        expression: "delighted",
        text: "That's how it starts. Then everyone brings a cake.",
      },
    ],
    reward: 'Lore card: "The barcode", stuck on a hen. She was not pleased.',
  },
  {
    id: 13,
    name: "The Market Stall",
    place: "Highmoor",
    cols: 6,
    rows: 8,
    path: [
      [0, 0],
      [5, 0],
      [5, 2],
      [1, 2],
      [1, 4],
      [5, 4],
      [5, 6],
      [2, 6],
      [2, 7],
    ],
    startMarks: 460,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall"],
    waves: ramp(7, { v: 8, d: 9 }),
    before: [
      {
        who: "narrator",
        text: "Tomas hauls an old trestle table into the lane, throws a striped cloth over it and hangs a sign: 'OPEN'. It is the most defiant thing anyone has done all week.",
      },
      {
        who: "tomas",
        text: "If we can't beat their prices, we'll beat their manners. Free tea with every turnip.",
      },
      {
        who: "cath",
        expression: "delighted",
        text: "New tool: the Market Stall. It earns Marks after every wave, and the towers beside it hit harder. Neighbours help neighbours. It's just good business.",
      },
    ],
    after: [
      {
        who: "tomas",
        text: "I sold eleven turnips and gave away forty cups of tea. I think I am the richest man in Highmoor.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Tomas, you're the only man in Highmoor who's still allowed to say that.",
      },
    ],
    reward:
      'Unlocked: the Market Stall (earns Marks and cheers on its neighbours). Lore card: "Free tea".',
  },
  {
    id: 14,
    name: "0.99",
    place: "Highmoor",
    cols: 6,
    rows: 8,
    path: [
      [0, 7],
      [0, 5],
      [4, 5],
      [4, 3],
      [1, 3],
      [1, 1],
      [5, 1],
      [5, 0],
    ],
    startMarks: 500,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall"],
    waves: ramp(7, { v: 6, d: 8, t: 2, truckFrom: 1 }),
    before: [
      {
        who: "narrator",
        text: 'A yellow lorry with a price on the side grinds up the hill: ".99". It is all the lorry says. It is all the lorry needs to say.',
      },
      {
        who: "bea",
        expression: "worried",
        text: "It goes bang and then two drones come out of it! Why does it do that?",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Because it's cheaper to be everywhere at once. Break the truck, and it just becomes more little problems.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "Hives on the bends, then. Little problems bunch up beautifully.",
      },
    ],
    after: [
      {
        who: "bea",
        expression: "delighted",
        text: "Gerald got four drones in one go. He is very proud.",
      },
      { who: "cath", expression: "wink", text: "As he should be." },
    ],
    reward: 'Lore card: "The .99 lorry", the paint smells of discount.',
  },
  {
    id: 15,
    name: "Loyalty Cards",
    place: "Highmoor",
    cols: 7,
    rows: 8,
    path: [
      [0, 0],
      [6, 0],
      [6, 2],
      [1, 2],
      [1, 4],
      [6, 4],
      [6, 6],
      [2, 6],
      [2, 7],
      [6, 7],
    ],
    startMarks: 540,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall"],
    waves: ramp(7, { v: 7, d: 9, t: 2 }),
    before: [
      {
        who: "narrator",
        text: 'Every house in Highmoor receives a small plastic card. It says "WELCOME BACK", though none of them have been anywhere.',
      },
      {
        who: "mara",
        text: "I got one too. It's asking for my postcode, my birthday and my favourite bean.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "It knows what you want before you do. That's not a loyalty card, Mara. That's a leash with a discount.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Ours is a punch card. Ten hedges, one free hedge.",
      },
    ],
    after: [
      {
        who: "mara",
        text: "I put mine in the compost. It is now the most useful thing it has ever been.",
      },
      {
        who: "cath",
        expression: "delighted",
        text: "That is the finest thing anyone has said this month.",
      },
    ],
    reward: 'Lore card: "The punch card", ten holes, one free hedge.',
  },
  {
    id: 16,
    name: "Mist on the Moor",
    place: "Highmoor",
    cols: 6,
    rows: 8,
    path: [
      [5, 0],
      [0, 0],
      [0, 2],
      [4, 2],
      [4, 4],
      [0, 4],
      [0, 6],
      [5, 6],
      [5, 7],
    ],
    startMarks: 540,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall"],
    waves: ramp(8, { v: 6, d: 8, t: 2, truckFrom: 1, vs: 1, ds: 1.1 }),
    before: [
      {
        who: "narrator",
        text: "A cold fog rolls down off the moor. In it, a hundred headlamps bob like lanterns at a very expensive funeral.",
      },
      {
        who: "tomas",
        text: "I can't see the road. I can't see my own hedges.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "You don't have to see the road, Tomas. You just have to know where it ends. Ours ends at the farmhouse, and they'll find that out.",
      },
    ],
    after: [
      {
        who: "tomas",
        text: "The fog lifted. Every truck was facing the wrong way.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "Someone turned the road signs round. I wonder who.",
      },
    ],
    reward:
      'Lore card: "Turned signs", every one of them now points at the pub.',
  },
  {
    id: 17,
    name: "The Auction",
    place: "Highmoor",
    cols: 6,
    rows: 8,
    path: [
      [0, 0],
      [4, 0],
      [4, 2],
      [1, 2],
      [1, 4],
      [5, 4],
      [5, 6],
      [0, 6],
      [0, 7],
      [5, 7],
    ],
    startMarks: 580,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall"],
    waves: ramp(8, { v: 8, d: 10, t: 3, truckFrom: 1, vs: 1.4 }),
    before: [
      {
        who: "narrator",
        text: "A tidy man with a gavel announces the auction of the Highmoor Market Square. He is bidding against himself and winning.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Nobody bid. Not one of you. Let him talk to the empty air until he runs out of pound coins.",
      },
      { who: "mara", text: "He's just raised his own offer again." },
      {
        who: "cath",
        expression: "wink",
        text: "Then we'd better make sure the square isn't for sale.",
      },
    ],
    after: [
      {
        who: "tomas",
        text: "The auctioneer left his gavel. I am using it to open jars.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "Going once. Going twice. Gone.",
      },
    ],
    reward: 'Lore card: "The gavel", currently a very good jar-opener.',
  },
  {
    id: 18,
    name: "Last Orders",
    place: "Highmoor",
    cols: 6,
    rows: 8,
    path: [
      [0, 1],
      [5, 1],
      [5, 3],
      [0, 3],
      [0, 5],
      [4, 5],
      [4, 7],
      [0, 7],
    ],
    startMarks: 600,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall"],
    waves: ramp(8, { v: 6, d: 8, t: 2, truckFrom: 1, vs: 1.1, ds: 1.1 }),
    before: [
      {
        who: "narrator",
        text: "The Highmoor Arms is the last pub in the valley that isn't owned by anyone with a slogan. The barman has locked the door and put out a sign: 'LAST ORDERS, LAST STAND'.",
      },
      {
        who: "tomas",
        text: "There are sixty people inside, all with a pint, all with an opinion.",
      },
      {
        who: "cath",
        expression: "delighted",
        text: "Sixty opinions is an army, Tomas. Let's put them in the lane.",
      },
    ],
    after: [
      {
        who: "tomas",
        text: "The pub is still ours. Someone bought a round for the hedges.",
      },
      { who: "cath", expression: "wink", text: "I'll have the same." },
    ],
    reward: 'Lore card: "The pub sign", a very cross-looking goose.',
  },
  {
    id: 19,
    name: "The Convoy Assembles",
    place: "Highmoor",
    cols: 7,
    rows: 8,
    path: [
      [6, 0],
      [0, 0],
      [0, 2],
      [5, 2],
      [5, 4],
      [1, 4],
      [1, 6],
      [6, 6],
      [6, 7],
    ],
    startMarks: 640,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall"],
    waves: ramp(8, { v: 7, d: 9, t: 2, truckFrom: 1, vs: 1.2, ds: 1.2 }),
    before: [
      {
        who: "narrator",
        text: "By dusk, the lorries are lined up along the ridge, nose to tail, headlamps on. There is a man in a very good coat walking down the line, and every driver sits up straighter as he passes.",
      },
      {
        who: "tomas",
        text: "That's Mr Crisp. He owns the prices. All of them. He sets them in the morning like a farmer feeds hens.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Tomorrow, he brings the whole convoy. Tonight, we get ready.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "worried",
        text: "That was only the advance party. The convoy proper is on its way down the hill.",
      },
      { who: "mara", text: "Then we had better have the kettle on." },
    ],
    reward:
      'Lore card: "Mr Crisp\'s coat", very good, very expensive, slightly damp.',
  },
  {
    id: 20,
    name: "Mr Crisp's Convoy",
    place: "Highmoor",
    cols: 6,
    rows: 8,
    path: [
      [0, 0],
      [5, 0],
      [5, 2],
      [0, 2],
      [0, 4],
      [5, 4],
      [5, 6],
      [0, 6],
      [0, 7],
      [5, 7],
    ],
    startMarks: 520,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall"],
    waves: [
      ...ramp(5, { v: 9, d: 11, t: 3, truckFrom: 0, vs: 1.4 }),
      [convoy(0), van(10, 1.2, 6), truck(4, 2, 10), drone(14, 0.55, 8)],
    ],
    before: [
      {
        who: "narrator",
        text: "Mr Crisp's Price-War Convoy is forty lorries long and every one of them is painted with a discount. At its head, the largest lorry in Highmoor's history. It has a tiny flag on the bonnet reading 'SAVE'.",
      },
      {
        who: "tomas",
        text: "He's offering to buy the whole square. He's offering a very good price. That's the horrible part.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "A very good price is just a very good trap, Tomas. Every stall, every hedge, every hive. Highmoor is not for sale.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "And when it breaks apart, that's when we sting them.",
      },
    ],
    after: [
      {
        who: "narrator",
        text: "The Convoy stands in the lane, in pieces. Mr Crisp steps down from the cab, looks at his ruined lorries and adjusts his coat. 'Fine,' he says. 'I'll take my business elsewhere.'",
      },
      { who: "tomas", text: "Where is elsewhere?" },
      {
        who: "cath",
        expression: "worried",
        text: "Somewhere with a coast. And somewhere with a podcast. I think Saltmarsh is about to have a very loud month.",
      },
    ],
    reward:
      'Act 2 complete. Lore card: "The .99 sign", now hanging above Tomas\'s market, corrected to a very fair price.',
  },
  {
    id: 21,
    name: "Salt and Static",
    place: "Saltmarsh",
    cols: 6,
    rows: 8,
    path: [
      [0, 1],
      [5, 1],
      [5, 3],
      [1, 3],
      [1, 5],
      [5, 5],
      [5, 7],
    ],
    startMarks: 650,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond"],
    waves: ramp(6, { v: 6, d: 7, t: 2, truckFrom: 3, i: 1, infFrom: 1 }),
    before: [
      {
        who: "narrator",
        text: "Saltmarsh is flat, wet and quiet, which is why Sol's podcast can be heard from the church tower. Overnight, it has been downloaded four million times.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Congratulations, Sol. You are now a target.",
      },
      {
        who: "narrator",
        text: "A glossy figure strides up the causeway, holding a phone at arm's length and narrating their own arrival. Every scarecrow turns to look.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "determined",
        text: "They don't shoot. They charm. Anything near an influencer forgets its job and starts watching.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "So we hit them first, or we hit them from far away. Duck Pond next, Sol. Slow the sparkle down.",
      },
    ],
    reward:
      'Unlocked: the Duck Pond (slows vehicles nearby, splashes the rest). Lore card: "Four million listens".',
  },
  {
    id: 22,
    name: "Going Live",
    place: "Saltmarsh",
    cols: 6,
    rows: 8,
    path: [
      [5, 0],
      [0, 0],
      [0, 2],
      [4, 2],
      [4, 4],
      [0, 4],
      [0, 6],
      [5, 6],
      [5, 7],
    ],
    startMarks: 650,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond"],
    waves: ramp(6, {
      v: 6,
      d: 8,
      t: 2,
      truckFrom: 2,
      i: 2,
      infFrom: 0,
      vs: 1.1,
    }),
    before: [
      {
        who: "narrator",
        text: "An influencer sets up a ring light in the middle of the causeway and announces a giveaway. There is nothing to win. Forty people are queueing anyway.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "The queue is the weapon. Anyone standing in it stops caring who is walking past them.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Ponds on the bends. Let them go live somewhere damp.",
      },
    ],
    after: [
      {
        who: "narrator",
        text: "The ring light ended up in a ditch. It is still on. It has never been so flattering to a frog.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "Sol, please don't put that in the episode.",
      },
    ],
    reward: 'Lore card: "The ring light", now the frog\'s.',
  },
  {
    id: 23,
    name: "Sponsored Tide",
    place: "Saltmarsh",
    cols: 6,
    rows: 8,
    path: [
      [0, 0],
      [5, 0],
      [5, 2],
      [0, 2],
      [0, 4],
      [5, 4],
      [5, 6],
      [1, 6],
      [1, 7],
      [5, 7],
    ],
    startMarks: 690,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond"],
    waves: ramp(7, {
      v: 7,
      d: 8,
      t: 2,
      truckFrom: 2,
      i: 2,
      infFrom: 1,
      vs: 1.1,
    }),
    before: [
      {
        who: "narrator",
        text: "The tide comes in with a logo on it. Someone has sponsored the sea.",
      },
      {
        who: "mara",
        text: "I can hear the ad read from here. It is very calm. It is coming from the water.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Never mind the sea. It's the little influencers in it I'm after.",
      },
    ],
    after: [
      {
        who: "mara",
        text: "The sea has gone back to being unsponsored. It looks relieved.",
      },
      { who: "cath", expression: "smirk", text: "Nobody asked the tide." },
    ],
    reward:
      'Lore card: "The sponsored sea", brought to you by absolutely nothing now.',
  },
  {
    id: 24,
    name: "Discount Code",
    place: "Saltmarsh",
    cols: 7,
    rows: 8,
    path: [
      [0, 7],
      [0, 5],
      [5, 5],
      [5, 3],
      [1, 3],
      [1, 1],
      [6, 1],
    ],
    startMarks: 710,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond"],
    waves: ramp(7, {
      v: 7,
      d: 9,
      t: 3,
      truckFrom: 2,
      i: 2,
      infFrom: 1,
      vs: 1.2,
    }),
    before: [
      {
        who: "narrator",
        text: "Every influencer on the marsh is reading out the same code at once: SAVE10. A truck with .99 on the side idles behind them, waiting for the crowd.",
      },
      {
        who: "bea",
        expression: "worried",
        text: "Cath, the truck and the influencer are holding hands!",
      },
      {
        who: "cath",
        expression: "determined",
        text: "That's the marketing department, sweetheart. They've discovered teamwork.",
      },
    ],
    after: [
      {
        who: "bea",
        expression: "delighted",
        text: "I drew them holding hands. Then I drew the pond splashing them.",
      },
      { who: "cath", expression: "wink", text: "Frame it." },
    ],
    reward: 'Lore card: "SAVE10", which saves nothing.',
  },
  {
    id: 25,
    name: "The Unboxing",
    place: "Saltmarsh",
    cols: 7,
    rows: 8,
    path: [
      [6, 0],
      [0, 0],
      [0, 2],
      [5, 2],
      [5, 4],
      [1, 4],
      [1, 6],
      [6, 6],
      [6, 7],
    ],
    startMarks: 730,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond"],
    waves: ramp(7, {
      v: 7,
      d: 9,
      t: 3,
      truckFrom: 1,
      i: 2,
      infFrom: 0,
      vs: 1.2,
    }),
    before: [
      {
        who: "narrator",
        text: "A very large box arrives at the causeway with a bow on it. A crowd forms. Someone films it from four angles.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "Don't open it. Whatever it is, that's what they want on camera.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Ponds beside the box. Let's see who gets the reveal.",
      },
    ],
    after: [
      {
        who: "narrator",
        text: "The box was full of other, smaller boxes. The smallest one held a coupon for a larger box.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "Marketing is just a very expensive game of pass the parcel.",
      },
    ],
    reward:
      'Lore card: "The smallest box", containing a coupon for a slightly larger box.',
  },
  {
    id: 26,
    name: "Comment Section",
    place: "Saltmarsh",
    cols: 6,
    rows: 8,
    path: [
      [0, 0],
      [5, 0],
      [5, 2],
      [1, 2],
      [1, 4],
      [5, 4],
      [5, 6],
      [0, 6],
      [0, 7],
      [5, 7],
    ],
    startMarks: 750,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond"],
    waves: ramp(8, {
      v: 8,
      d: 9,
      t: 3,
      truckFrom: 1,
      i: 2,
      infFrom: 0,
      vs: 1.2,
    }),
    before: [
      {
        who: "narrator",
        text: "By noon the podcast's comment section is on fire. Half the comments are real, and the other half share a very consistent tone.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Sol, your listeners are fine. It's the ones who want to be your listeners that I'd watch.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Everyone on the causeway, stay off your phones. Well. Except Sol.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "smirk",
        text: "Delete the ones with a smiling face and a discount code. You'll spot them.",
      },
      {
        who: "mara",
        text: "Or just don't read them. It's what I do with the weather forecast.",
      },
    ],
    reward: 'Lore card: "Top comment", nine hundred likes, none of them real.',
  },
  {
    id: 27,
    name: "Brand Deal",
    place: "Saltmarsh",
    cols: 6,
    rows: 8,
    path: [
      [0, 1],
      [5, 1],
      [5, 3],
      [0, 3],
      [0, 5],
      [5, 5],
      [5, 7],
      [1, 7],
    ],
    startMarks: 770,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond"],
    waves: ramp(8, {
      v: 8,
      d: 10,
      t: 3,
      truckFrom: 1,
      i: 2,
      infFrom: 0,
      vs: 1.3,
    }),
    before: [
      {
        who: "narrator",
        text: "A man in a very good blazer offers Sol a great deal of money to say one particular yoghurt is the only yoghurt worth eating.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Say no, Sol. Then say it on air, so everyone hears.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Ponds ready. The blazer's about to get very wet.",
      },
    ],
    after: [
      {
        who: "narrator",
        text: "Sol said no. Four million people heard. The yoghurt's share price fell by a whole biscuit.",
      },
      {
        who: "cath",
        expression: "delighted",
        text: "That's how you do an ad read.",
      },
    ],
    reward: 'Lore card: "The refusal", four minutes long and very polite.',
  },
  {
    id: 28,
    name: "Golden Hour",
    place: "Saltmarsh",
    cols: 7,
    rows: 8,
    path: [
      [6, 0],
      [1, 0],
      [1, 2],
      [6, 2],
      [6, 4],
      [0, 4],
      [0, 6],
      [5, 6],
      [5, 7],
    ],
    startMarks: 790,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond"],
    waves: ramp(8, {
      v: 8,
      d: 10,
      t: 3,
      truckFrom: 1,
      i: 2,
      infFrom: 0,
      vs: 1.3,
      ds: 1.5,
    }),
    before: [
      {
        who: "narrator",
        text: "The marsh at sunset is the most beautiful thing in the county, and forty influencers have arrived to stand in front of it.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "They'll fill the lane with filters. Every tower will be looking at the sunset.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Then we out-stare them. Ponds and stalls, and don't blink.",
      },
    ],
    after: [
      {
        who: "mara",
        text: "I have never seen so many people photograph a puddle.",
      },
      { who: "cath", expression: "wink", text: "It was a good puddle." },
    ],
    reward: 'Lore card: "The good puddle", photographed nine hundred times.',
  },
  {
    id: 29,
    name: "The Blimp Rises",
    place: "Saltmarsh",
    cols: 7,
    rows: 8,
    path: [
      [0, 0],
      [5, 0],
      [5, 2],
      [0, 2],
      [0, 4],
      [6, 4],
      [6, 6],
      [1, 6],
      [1, 7],
      [6, 7],
    ],
    startMarks: 810,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond"],
    waves: ramp(8, {
      v: 8,
      d: 10,
      t: 3,
      truckFrom: 1,
      i: 2,
      infFrom: 0,
      vs: 1.3,
      ds: 1.5,
    }),
    before: [
      {
        who: "narrator",
        text: "A shape rises over the sea. It is pink, enormous, and has the word BLESSED across its side in a very rounded font.",
      },
      {
        who: "bea",
        expression: "worried",
        text: "It's a balloon. It's looking at us.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "It's a very large advert, sweetheart. Tomorrow, it comes to say hello. Tonight we make sure nothing is left for it to sell.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "worried",
        text: "Everything within a couple of cells of that blimp will stop working. Put the ponds and hives at the edges.",
      },
      { who: "mara", text: "I'll put the kettle on. And a second kettle." },
    ],
    reward: 'Lore card: "BLESSED", in a very rounded font.',
  },
  {
    id: 30,
    name: "Brand Ambassador",
    place: "Saltmarsh",
    cols: 6,
    rows: 8,
    path: [
      [0, 0],
      [5, 0],
      [5, 2],
      [0, 2],
      [0, 4],
      [5, 4],
      [5, 6],
      [0, 6],
      [0, 7],
      [5, 7],
    ],
    startMarks: 900,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond"],
    waves: [
      ...ramp(5, {
        v: 9,
        d: 11,
        t: 3,
        truckFrom: 0,
        i: 2,
        infFrom: 0,
        vs: 1.4,
      }),
      [blimp(0), van(10, 1.2, 6), influencer(3, 2.6, 8), drone(14, 0.55, 10)],
    ],
    before: [
      {
        who: "narrator",
        text: "The Brand Ambassador Blimp drifts over Saltmarsh at walking pace. It plays a song. The song is about how you love the blimp. Everyone below starts humming.",
      },
      {
        who: "sol",
        text: "I can hear it. I can hear it in the microphone. I can't turn it off.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Then we fight it in the quiet. Hold the lane, close in, and when it charms the towers near it, pie it. Pie stops everything for a moment.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Nobody has ever been a brand ambassador for very long.",
      },
    ],
    after: [
      {
        who: "narrator",
        text: "The Blimp comes down slowly in the shallows and deflates with a long, sad, well-produced sigh. Someone pins a note to it: 'Not sponsored.'",
      },
      {
        who: "sol",
        text: "I'm calling the episode 'Quiet'. Just forty minutes of the marsh.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "Rivermead's next. There are bulldozers, and a river that is not in a good mood. Bring boots.",
      },
    ],
    reward:
      'Act 3 complete. Lore card: "Not sponsored", pinned to a very large sigh.',
  },
  {
    id: 31,
    name: "The River Rises",
    place: "Rivermead",
    cols: 6,
    rows: 8,
    path: [
      [0, 1],
      [5, 1],
      [5, 3],
      [0, 3],
      [0, 5],
      [5, 5],
      [5, 7],
    ],
    startMarks: 950,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond", "barn"],
    waves: ramp(7, { v: 8, d: 9, t: 3, truckFrom: 1, b: 1, bFrom: 2, vs: 1.2 }),
    before: [
      {
        who: "narrator",
        text: "Rivermead in October. The river has come up over the lower field and taken a bench, two geese and a very good gate.",
      },
      {
        who: "tomas",
        text: "The council promised a flood wall. What they've sent is a bulldozer. To clear the 'obstruction', meaning us.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Bulldozers are armoured, so scarecrow turnips just bounce. But the neighbours are coming, and they've got a barn.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "New tool: the Co-op Barn. Farmhands pour out and block the lane. Nobody gets past a queue of cross people in wellies.",
      },
    ],
    after: [
      {
        who: "mara",
        text: "The bulldozer sat in the lane for a full minute, then reversed out. I think it was embarrassed.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "It was outnumbered by a woman with a thermos. It happens.",
      },
    ],
    reward:
      'Unlocked: the Co-op Barn (farmhands block the lane). Lore card: "The bench", found in a tree.',
  },
  {
    id: 32,
    name: "Sandbag Sunday",
    place: "Rivermead",
    cols: 7,
    rows: 8,
    path: [
      [6, 0],
      [1, 0],
      [1, 2],
      [6, 2],
      [6, 4],
      [0, 4],
      [0, 6],
      [5, 6],
      [5, 7],
    ],
    startMarks: 970,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond", "barn"],
    waves: ramp(8, { v: 8, d: 9, t: 3, truckFrom: 1, b: 1, bFrom: 1, vs: 1.2 }),
    before: [
      {
        who: "narrator",
        text: "Sunday. Every farm in Rivermead is filling sandbags and every child is doing it wrong, enthusiastically.",
      },
      {
        who: "bea",
        expression: "delighted",
        text: "I made a sandbag castle! It has a moat. Is that too much moat?",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Never. But save some sand, sweetheart. The bulldozers are back and they've brought a friend.",
      },
    ],
    after: [
      {
        who: "bea",
        expression: "delighted",
        text: "The castle held! The moat did most of it.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "A brilliant moat. Put it on the plans.",
      },
    ],
    reward: 'Lore card: "The moat", officially too much moat.',
  },
  {
    id: 33,
    name: "Compulsory Purchase",
    place: "Rivermead",
    cols: 6,
    rows: 8,
    path: [
      [0, 0],
      [5, 0],
      [5, 2],
      [1, 2],
      [1, 4],
      [5, 4],
      [5, 6],
      [0, 6],
      [0, 7],
      [5, 7],
    ],
    startMarks: 990,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond", "barn"],
    waves: ramp(8, {
      v: 8,
      d: 9,
      t: 3,
      truckFrom: 1,
      i: 1,
      infFrom: 2,
      b: 2,
      bFrom: 1,
      vs: 1.2,
    }),
    before: [
      {
        who: "narrator",
        text: "A letter arrives in twelve languages, and every one of them says the mill will be knocked down on Friday for 'the greater good of shareholders'.",
      },
      {
        who: "mara",
        text: "It's a compulsory purchase order. It's got a lovely watermark.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "It's got a loophole too. It needs the mill to be empty. Nobody leave the mill.",
      },
    ],
    after: [
      {
        who: "tomas",
        text: "Forty people slept in the mill. Someone brought a harp.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Friday came and went. The order expired at midnight, politely.",
      },
    ],
    reward: 'Lore card: "The watermark", very hard to forge, easy to ignore.',
  },
  {
    id: 34,
    name: "The Ford",
    place: "Rivermead",
    cols: 7,
    rows: 8,
    path: [
      [0, 1],
      [6, 1],
      [6, 3],
      [0, 3],
      [0, 5],
      [6, 5],
      [6, 7],
      [1, 7],
    ],
    startMarks: 1010,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond", "barn"],
    waves: ramp(8, {
      v: 8,
      d: 10,
      t: 3,
      truckFrom: 1,
      b: 2,
      bFrom: 1,
      vs: 1.3,
      ds: 1.5,
    }),
    before: [
      {
        who: "narrator",
        text: "The ford is the only crossing for eleven miles. The bulldozers want it, because it is in the way of a car park.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "Three convoys at once, and the ford is narrow. Barns at the bends. Let them queue.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "smirk",
        text: "Water finds its level. So do bulldozers.",
      },
      {
        who: "mara",
        text: "Somebody's going to have to fish that one out. I'll bring a rope.",
      },
    ],
    reward: 'Lore card: "The ford", eleven miles from any alternative.',
  },
  {
    id: 35,
    name: "Silt and Sense",
    place: "Rivermead",
    cols: 7,
    rows: 8,
    path: [
      [6, 0],
      [0, 0],
      [0, 2],
      [5, 2],
      [5, 4],
      [1, 4],
      [1, 6],
      [6, 6],
      [6, 7],
    ],
    startMarks: 1030,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond", "barn"],
    waves: ramp(9, {
      v: 8,
      d: 10,
      t: 3,
      truckFrom: 1,
      i: 1,
      infFrom: 2,
      b: 2,
      bFrom: 1,
      vs: 1.3,
    }),
    before: [
      {
        who: "narrator",
        text: "The flood has gone and left an inch of silt on everything. A pink pop-up shop has appeared on the silt, selling 'flood-chic'.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "They're selling our flood back to us. Tomas, tell me you're not buying a wet-look tote.",
      },
      { who: "tomas", text: "I already have one. For the mud." },
    ],
    after: [
      {
        who: "cath",
        expression: "wink",
        text: "The pop-up closed by lunchtime. The tote, I'm told, is still very useful.",
      },
    ],
    reward: 'Lore card: "Flood-chic", one tote, slightly damp.',
  },
  {
    id: 36,
    name: "The Barn Raising",
    place: "Rivermead",
    cols: 7,
    rows: 8,
    path: [
      [0, 0],
      [6, 0],
      [6, 2],
      [0, 2],
      [0, 4],
      [6, 4],
      [6, 6],
      [0, 6],
      [0, 7],
      [6, 7],
    ],
    startMarks: 1050,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond", "barn"],
    waves: ramp(9, {
      v: 9,
      d: 10,
      t: 3,
      truckFrom: 1,
      b: 2,
      bFrom: 0,
      vs: 1.3,
    }),
    before: [
      {
        who: "narrator",
        text: "By morning there are three hundred people in the field with hammers. Nobody sent an invitation. Everyone brought a plank.",
      },
      {
        who: "cath",
        expression: "delighted",
        text: "That is what a barn-raising looks like. Look at them. That is the whole thing they can't put in a spreadsheet.",
      },
      {
        who: "bea",
        expression: "delighted",
        text: "I'm in charge of biscuits!",
      },
    ],
    after: [
      {
        who: "mara",
        text: "Built by dinner. Painted by supper. It is slightly crooked and I love it.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Crooked is how you know it's homemade.",
      },
    ],
    reward: 'Lore card: "Three hundred planks", none of them the same size.',
  },
  {
    id: 37,
    name: "Dozer Alley",
    place: "Rivermead",
    cols: 7,
    rows: 8,
    path: [
      [0, 0],
      [5, 0],
      [5, 2],
      [0, 2],
      [0, 4],
      [6, 4],
      [6, 6],
      [1, 6],
      [1, 7],
      [6, 7],
    ],
    startMarks: 1070,
    goodwill: 10,
    towers: ["hedgerow", "scarecrow", "beehive", "stall", "pond", "barn"],
    waves: ramp(9, {
      v: 9,
      d: 10,
      t: 3,
      truckFrom: 1,
      i: 1,
      infFrom: 3,
      b: 3,
      bFrom: 0,
      vs: 1.3,
    }),
    before: [
      {
        who: "narrator",
        text: "Six bulldozers in a line, engines running, and a man in a hard hat holding a clipboard he has never once looked at.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "They're armoured, so I want everything that hits hard. Get the barns thick at the corners.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "smirk",
        text: "Someone should tell him the clipboard is upside down.",
      },
      { who: "mara", text: "Somebody did. He wrote it down." },
    ],
    reward: 'Lore card: "The clipboard", upside down, never read.',
  },
  {
    id: 38,
    name: "The Grain Silo",
    place: "Rivermead",
    cols: 7,
    rows: 8,
    path: [
      [6, 1],
      [0, 1],
      [0, 3],
      [6, 3],
      [6, 5],
      [0, 5],
      [0, 7],
      [5, 7],
    ],
    startMarks: 1100,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
    ],
    waves: ramp(9, {
      v: 9,
      d: 10,
      t: 3,
      truckFrom: 1,
      b: 3,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      vs: 1.4,
    }),
    before: [
      {
        who: "narrator",
        text: "Ines's father built the old silo in 1961 and never once used it for anything except being tall. It turns out to be excellent at throwing grain.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "New tool: the Grain Silo. Slow, heavy, and it ignores armour entirely. Bulldozers are going to learn something.",
      },
    ],
    after: [
      { who: "mara", text: "That silo hasn't worked in sixty years." },
      {
        who: "cath",
        expression: "smirk",
        text: "It was waiting for a reason.",
      },
    ],
    reward:
      'Unlocked: the Grain Silo (heavy shot that ignores armour). Lore card: "1961".',
  },
  {
    id: 39,
    name: "High Water",
    place: "Rivermead",
    cols: 7,
    rows: 8,
    path: [
      [0, 0],
      [6, 0],
      [6, 2],
      [0, 2],
      [0, 4],
      [6, 4],
      [6, 6],
      [0, 6],
      [0, 7],
      [6, 7],
    ],
    startMarks: 1120,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
    ],
    waves: ramp(9, {
      v: 9,
      d: 11,
      t: 4,
      truckFrom: 1,
      b: 3,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      vs: 1.4,
      ds: 1.5,
    }),
    before: [
      {
        who: "narrator",
        text: "The night before the Mega-Dozer, the river comes up again. The whole valley is on the ridge with lanterns.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "It's the biggest machine they've ever built. It has the word SYNERGY painted on it, in red. They're terribly proud.",
      },
      { who: "bea", expression: "worried", text: "Will we be all right?" },
      {
        who: "cath",
        expression: "smirk",
        text: "We will. Everyone's here, sweetheart. That's the plan.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "determined",
        text: "Get some sleep. Tomorrow we put a silo in the way of a very large idea.",
      },
    ],
    reward: 'Lore card: "Lanterns on the ridge", three hundred of them.',
  },
  {
    id: 40,
    name: "The Mega-Dozer",
    place: "Rivermead",
    cols: 7,
    rows: 8,
    path: [
      [0, 0],
      [6, 0],
      [6, 2],
      [0, 2],
      [0, 4],
      [6, 4],
      [6, 6],
      [0, 6],
      [0, 7],
      [6, 7],
    ],
    startMarks: 1250,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
    ],
    waves: [
      ...ramp(6, {
        v: 9,
        d: 11,
        t: 3,
        truckFrom: 0,
        b: 3,
        bFrom: 0,
        i: 1,
        infFrom: 3,
        vs: 1.4,
      }),
      [megadozer(0), bulldozer(4, 3, 6), van(12, 1.2, 8), drone(14, 0.55, 10)],
    ],
    before: [
      {
        who: "narrator",
        text: "The Mega-Dozer comes down the valley at dawn, and the ground shakes in a gentle, well-tested way. It is the size of a house. It has a slogan.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "It's armoured and it splits into bulldozers when it dies. Silos on it, barns to hold it, and pie when it gets close.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "They called it Synergy. I'd call it a very large door.",
      },
    ],
    after: [
      {
        who: "narrator",
        text: "It stops in the middle of the ford, sighs, and falls into two smaller bulldozers, which are quickly dealt with. Somebody starts to clap.",
      },
      {
        who: "tomas",
        text: "The river's going down. The valley's still ours.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "Oakvale's next. Ines says something is wrong with the water, and the people selling it are very calm about it.",
      },
    ],
    reward:
      'Act 4 complete. Lore card: "Synergy", painted in red, slightly chipped.',
  },
  {
    id: 41,
    name: "Oakvale Water",
    place: "Oakvale",
    cols: 7,
    rows: 8,
    path: [
      [6, 1],
      [0, 1],
      [0, 3],
      [6, 3],
      [6, 5],
      [0, 5],
      [0, 7],
      [5, 7],
    ],
    startMarks: 1300,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
    ],
    waves: ramp(9, {
      v: 10,
      d: 11,
      t: 3,
      truckFrom: 1,
      b: 3,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      vs: 1.4,
    }),
    before: [
      {
        who: "narrator",
        text: "Oakvale is all orchards and slow rivers, and this spring the tap water tastes very slightly of nothing at all. Ines, the district nurse, has noticed.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Ines rang me at six. She says a company called Candor has bought the spring and is selling the water back to the village, in bottles, with a leaf on.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "There's a leaf on it. That's how you know it's honest.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "wink",
        text: "Nobody in Oakvale is buying the leaf. Ines is going to want to see the paperwork.",
      },
    ],
    reward: 'Lore card: "The leaf", a very small logo on a very large bottle.',
  },
  {
    id: 42,
    name: "Spring Water",
    place: "Oakvale",
    cols: 7,
    rows: 8,
    path: [
      [0, 0],
      [6, 0],
      [6, 2],
      [0, 2],
      [0, 4],
      [6, 4],
      [6, 6],
      [0, 6],
      [0, 7],
      [6, 7],
    ],
    startMarks: 1320,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
    ],
    waves: ramp(9, {
      v: 10,
      d: 12,
      t: 3,
      truckFrom: 1,
      b: 3,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      vs: 1.4,
      ds: 1.5,
    }),
    before: [
      {
        who: "narrator",
        text: "The bottled-water trucks come up the orchard road in convoy, each with a sticker reading WELLNESS. The orchard cats watch from the wall.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "They've sent bulldozers to put in a pipeline. Which is a strange way to help anyone stay well.",
      },
    ],
    after: [
      {
        who: "mara",
        text: "You'd think a wellness company would be less keen on knocking down a wall.",
      },
    ],
    reward: 'Lore card: "Wellness", printed in a cheerful, rounded typeface.',
  },
  {
    id: 43,
    name: "The Leaflet",
    place: "Oakvale",
    cols: 7,
    rows: 8,
    path: [
      [6, 1],
      [0, 1],
      [0, 3],
      [6, 3],
      [6, 5],
      [0, 5],
      [0, 7],
      [5, 7],
    ],
    startMarks: 1340,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
    ],
    waves: ramp(9, {
      v: 11,
      d: 12,
      t: 4,
      truckFrom: 1,
      b: 3,
      bFrom: 0,
      i: 2,
      infFrom: 2,
      vs: 1.4,
      ds: 1.5,
    }),
    before: [
      {
        who: "narrator",
        text: "Every doorstep in Oakvale gets a glossy leaflet. It promises that tap water is, technically, a risk.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "It says 'may contain traces of nature'. It's a very clever sentence. It doesn't say anything at all.",
      },
    ],
    after: [
      {
        who: "bea",
        expression: "smirk",
        text: "I put the leaflet in the compost. The worms didn't like it either.",
      },
    ],
    reward: 'Lore card: "Traces of nature", underlined twice in Ines\'s pen.',
  },
  {
    id: 44,
    name: "Unlabelled",
    place: "Oakvale",
    cols: 7,
    rows: 8,
    path: [
      [0, 0],
      [6, 0],
      [6, 2],
      [0, 2],
      [0, 4],
      [6, 4],
      [6, 6],
      [0, 6],
      [0, 7],
      [6, 7],
    ],
    startMarks: 1360,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
    ],
    waves: ramp(9, {
      v: 10,
      d: 12,
      t: 3,
      truckFrom: 1,
      b: 3,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      vs: 1.3,
      ds: 1.5,
      p: 1,
      pFrom: 6,
    }),
    before: [
      {
        who: "narrator",
        text: "Something new comes up the lane: plain grey vans with no logo, no plate, and a question mark where the name should be. The cameras don't seem to see them.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "They're not on the towers' lists. Whatever they are, they slip past. We can hold the line, but something is getting through.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "determined",
        text: "Sol says there's a fix. He's building it on top of the cider press. Don't ask.",
      },
    ],
    reward:
      'Lore card: "Question mark", painted on the side of a plain grey van.',
  },
  {
    id: 45,
    name: "Sol's Antenna",
    place: "Oakvale",
    cols: 7,
    rows: 8,
    path: [
      [6, 1],
      [0, 1],
      [0, 3],
      [6, 3],
      [6, 5],
      [0, 5],
      [0, 7],
      [5, 7],
    ],
    startMarks: 1400,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
    ],
    waves: ramp(9, {
      v: 10,
      d: 12,
      t: 3,
      truckFrom: 1,
      b: 3,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      vs: 1.3,
      ds: 1.5,
      p: 3,
      pFrom: 1,
    }),
    before: [
      {
        who: "sol",
        text: "Right. It's a mast. It's an antenna, mostly, and a lot of enthusiasm. When something's hiding, it lights up and everybody can see it.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "New tool: the Radio Mast. It shows up stealth units in range and marks whatever it sees, so every tower hits harder.",
      },
      {
        who: "sol",
        text: "I also tuned it to the parish radio. Ignore the Sunday hymn.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "delighted",
        text: "Sol, that's the best thing you've ever built.",
      },
    ],
    reward:
      'Unlocked: the Radio Mast (reveals stealth units and marks targets). Lore card: "Sunday hymn", faintly audible on the mast.',
  },
  {
    id: 46,
    name: "Static",
    place: "Oakvale",
    cols: 7,
    rows: 8,
    path: [
      [0, 0],
      [6, 0],
      [6, 2],
      [0, 2],
      [0, 4],
      [6, 4],
      [6, 6],
      [0, 6],
      [0, 7],
      [6, 7],
    ],
    startMarks: 1420,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
    ],
    waves: ramp(9, {
      v: 11,
      d: 12,
      t: 4,
      truckFrom: 1,
      b: 4,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      vs: 1.3,
      ds: 1.5,
      p: 3,
      pFrom: 0,
    }),
    before: [
      {
        who: "narrator",
        text: "The plain grey vans multiply. Every one of them is one the bulldozers can walk behind.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Masts near the bends, silos behind them. If they can't hide, they're just vans with a bad attitude.",
      },
    ],
    after: [
      {
        who: "sol",
        text: "I've never been so pleased to be told off by a radio.",
      },
    ],
    reward: 'Lore card: "Static", the good kind.',
  },
  {
    id: 47,
    name: "Ines Speaks",
    place: "Oakvale",
    cols: 7,
    rows: 8,
    path: [
      [6, 1],
      [0, 1],
      [0, 3],
      [6, 3],
      [6, 5],
      [0, 5],
      [0, 7],
      [5, 7],
    ],
    startMarks: 1440,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
    ],
    waves: ramp(9, {
      v: 11,
      d: 13,
      t: 4,
      truckFrom: 1,
      b: 4,
      bFrom: 0,
      i: 2,
      infFrom: 2,
      vs: 1.4,
      ds: 1.5,
      p: 3,
      pFrom: 0,
    }),
    before: [
      {
        who: "narrator",
        text: "Ines stands on a hay bale in the market square, holding up two glasses of water. One is from the tap. One is from the leaf bottle. She asks the village to taste them.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "She made a scientist's argument. It only takes a pause and a tasting.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "delighted",
        text: "Half the village voted for the tap before she'd finished the sentence. The other half were still thinking, which counts.",
      },
    ],
    reward: 'Lore card: "Two glasses", side by side on a hay bale.',
  },
  {
    id: 48,
    name: "Cold Chain",
    place: "Oakvale",
    cols: 7,
    rows: 8,
    path: [
      [0, 0],
      [6, 0],
      [6, 2],
      [0, 2],
      [0, 4],
      [6, 4],
      [6, 6],
      [0, 6],
      [0, 7],
      [6, 7],
    ],
    startMarks: 1460,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
    ],
    waves: ramp(9, {
      v: 11,
      d: 13,
      t: 4,
      truckFrom: 1,
      b: 4,
      bFrom: 0,
      i: 2,
      infFrom: 2,
      vs: 1.4,
      ds: 1.5,
      p: 4,
      pFrom: 0,
    }),
    before: [
      {
        who: "narrator",
        text: "Candor sends its refrigerated fleet, white and humming and utterly silent, and behind it a very tall man in a very clean coat.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "That's Dr Vane. He runs the wellness division. He talks as if everyone were his patient, and he's never once been ill himself.",
      },
    ],
    after: [
      {
        who: "mara",
        text: "He said we'd feel better if we let him help. I said I felt fine, thank you.",
      },
    ],
    reward: 'Lore card: "Dr Vane", who has never been seen to sweat.',
  },
  {
    id: 49,
    name: "The Night Before",
    place: "Oakvale",
    cols: 7,
    rows: 8,
    path: [
      [6, 1],
      [0, 1],
      [0, 3],
      [6, 3],
      [6, 5],
      [0, 5],
      [0, 7],
      [5, 7],
    ],
    startMarks: 1480,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
    ],
    waves: ramp(9, {
      v: 11,
      d: 14,
      t: 4,
      truckFrom: 1,
      b: 4,
      bFrom: 0,
      i: 2,
      infFrom: 2,
      vs: 1.4,
      ds: 1.5,
      p: 4,
      pFrom: 0,
    }),
    before: [
      {
        who: "narrator",
        text: "The whole of Oakvale is awake. There are apples on every doorstep, and Bea has drawn a picture of the tap with a cape on.",
      },
      {
        who: "bea",
        expression: "determined",
        text: "Can I help on the mast? I'll hold the torch.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "You hold the torch. I'll do the shouting.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "determined",
        text: "Tomorrow the clinic comes to us. Fine. We'll give it a very warm welcome.",
      },
    ],
    reward: 'Lore card: "The tap in a cape", drawn by Bea, framed by Ines.',
  },
  {
    id: 50,
    name: "Vane's Clinic-in-a-Box",
    place: "Oakvale",
    cols: 7,
    rows: 8,
    path: [
      [0, 0],
      [6, 0],
      [6, 2],
      [0, 2],
      [0, 4],
      [6, 4],
      [6, 6],
      [0, 6],
      [0, 7],
      [6, 7],
    ],
    startMarks: 1600,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
    ],
    waves: [
      ...ramp(6, {
        v: 11,
        d: 13,
        t: 4,
        truckFrom: 0,
        b: 4,
        bFrom: 0,
        i: 2,
        infFrom: 2,
        vs: 1.4,
        ds: 1.5,
        p: 4,
        pFrom: 0,
      }),
      [
        clinic(0),
        phantom(4, 2, 6),
        bulldozer(4, 3, 8),
        van(12, 1.2, 8),
        drone(14, 0.55, 10),
      ],
    ],
    before: [
      {
        who: "narrator",
        text: "It arrives at nine o'clock, precisely, a white box the size of a chapel with a green cross on the side. A door opens in it. A very calm voice says, 'We're here to help.'",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Vane's Clinic-in-a-Box. It heals everything beside it, so keep the pressure on. It drops three unmarked vans when it goes, and only a mast will show you where they are.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Ines is holding the front door. Sol is holding the mast. Bea is holding the torch. I'm holding the pie.",
      },
    ],
    after: [
      {
        who: "narrator",
        text: "The Clinic shudders, gently, and opens. Inside there is a desk, a leaflet, and no doctor at all. The plain grey vans scatter and are mopped up.",
      },
      {
        who: "mara",
        text: "He never came himself, did he.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "He never does.",
      },
      {
        who: "narrator",
        text: "Ines pins a note to the front of the empty box: 'Tap water, free, since forever.' It stays there all night.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "Shingle Bay next. There's a storm coming in, and the fishing fleet has asked for us by name.",
      },
    ],
    reward:
      'Act 5 complete. Lore card: "Free since forever", pinned to an empty box.',
  },
  {
    id: 51,
    name: "Shingle Bay",
    place: "Shingle Bay",
    cols: 7,
    rows: 8,
    path: [
      [0, 1],
      [5, 1],
      [5, 3],
      [1, 3],
      [1, 5],
      [6, 5],
      [6, 7],
      [2, 7],
    ],
    startMarks: 1700,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
    ],
    waves: ramp(9, {
      v: 11,
      d: 13,
      t: 4,
      truckFrom: 1,
      b: 3,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      p: 3,
      pFrom: 1,
      vs: 1.4,
      ds: 1.5,
      e: 2,
      eFrom: 4,
    }),
    before: [
      {
        who: "narrator",
        text: "Shingle Bay smells of salt and diesel. The fishing fleet is in, and the harbour master has hung a hand-lettered sign: NO ENTRY, BY ORDER OF NOBODY WHO LIVES HERE.",
      },
      {
        who: "tomas",
        text: "They want the quay for a distribution hub. The boats have been here three hundred years.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Then it's a very old argument, and we're on the side of the boats.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "smirk",
        text: "The first tenders turned back at the harbour wall. The gulls have decided who they're voting for.",
      },
    ],
    reward: 'Lore card: "The sign", still hanging, still very rude.',
  },
  {
    id: 52,
    name: "Low Tide",
    place: "Shingle Bay",
    cols: 7,
    rows: 8,
    path: [
      [0, 0],
      [6, 0],
      [6, 2],
      [0, 2],
      [0, 4],
      [6, 4],
      [6, 6],
      [0, 6],
      [0, 7],
      [6, 7],
    ],
    startMarks: 1720,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
    ],
    waves: ramp(9, {
      v: 11,
      d: 13,
      t: 4,
      truckFrom: 1,
      b: 3,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      p: 3,
      pFrom: 1,
      vs: 1.4,
      ds: 1.5,
      e: 2,
      eFrom: 3,
    }),
    before: [
      {
        who: "narrator",
        text: "At low tide the harbour is mostly mud, and the corporations' little fast boats, the tenders, come in on the lanes the water leaves.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Tenders are quick and half-armoured. Silos hurt them, and so do patient people.",
      },
    ],
    after: [
      {
        who: "tomas",
        text: "My grandfather said the tide gave you five minutes of grace. He never said what to do with them.",
      },
    ],
    reward: 'Lore card: "Five minutes of grace", on the tide table.',
  },
  {
    id: 53,
    name: "Net Mending",
    place: "Shingle Bay",
    cols: 7,
    rows: 8,
    path: [
      [6, 1],
      [0, 1],
      [0, 3],
      [6, 3],
      [6, 5],
      [0, 5],
      [0, 7],
      [5, 7],
    ],
    startMarks: 1740,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
    ],
    waves: ramp(9, {
      v: 11,
      d: 13,
      t: 4,
      truckFrom: 1,
      b: 3,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      p: 3,
      pFrom: 1,
      vs: 1.4,
      ds: 1.5,
      e: 3,
      eFrom: 3,
    }),
    before: [
      {
        who: "narrator",
        text: "The whole fleet sits on the quay mending nets and swapping opinions about the harbour authority, none of them printable.",
      },
      {
        who: "bea",
        expression: "smirk",
        text: "I'm mending a net. It has a hole shaped like a fish. Is that on purpose?",
      },
      {
        who: "cath",
        expression: "wink",
        text: "Only if the fish agrees.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "delighted",
        text: "The nets are back on the wall, and the tenders have stopped coming near it.",
      },
    ],
    reward: 'Lore card: "Net with a fish-shaped hole".',
  },
  {
    id: 54,
    name: "The Storm Warning",
    place: "Shingle Bay",
    cols: 7,
    rows: 8,
    path: [
      [0, 0],
      [6, 0],
      [6, 2],
      [0, 2],
      [0, 4],
      [6, 4],
      [6, 6],
      [0, 6],
      [0, 7],
      [6, 7],
    ],
    startMarks: 1760,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
    ],
    waves: ramp(9, {
      v: 11,
      d: 13,
      t: 4,
      truckFrom: 1,
      b: 3,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      p: 3,
      pFrom: 1,
      vs: 1.4,
      e: 3,
      eFrom: 2,
      ds: 1.6,
    }),
    before: [
      {
        who: "narrator",
        text: "The barometer falls, gulls fly inland, and Cath's hair does something dramatic and windswept. She finds this a little unfair.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "A storm is due tonight. Candor knows. They're timing the landing for when nobody can see.",
      },
    ],
    after: [
      {
        who: "sol",
        text: "I'll keep the mast up. If it falls, it falls as a mast, gloriously.",
      },
    ],
    reward: 'Lore card: "Barometer", tapped by a worried harbour master.',
  },
  {
    id: 55,
    name: "Ines's Tent",
    place: "Shingle Bay",
    cols: 7,
    rows: 8,
    path: [
      [0, 1],
      [5, 1],
      [5, 3],
      [1, 3],
      [1, 5],
      [6, 5],
      [6, 7],
      [2, 7],
    ],
    startMarks: 1800,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
      "tent",
    ],
    waves: ramp(9, {
      v: 11,
      d: 13,
      t: 4,
      truckFrom: 1,
      b: 3,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      p: 3,
      pFrom: 1,
      vs: 1.4,
      e: 3,
      eFrom: 2,
      ds: 1.6,
    }),
    before: [
      {
        who: "narrator",
        text: "Ines has arrived with a tent, a kettle and two enormous flasks. It is white with a green cross, but hers is hand-sewn and slightly crooked.",
      },
      {
        who: "cath",
        expression: "wink",
        text: "New tool: the Clinic Tent. Towers beside it shake off influencer charm and fire faster. Ines calls it 'a cup of tea and a good sit down'.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "smirk",
        text: "There's nothing quite like tea to show a sea captain who's in charge.",
      },
    ],
    reward:
      'Unlocked: the Clinic Tent (cleanses charm, buffs nearby towers). Lore card: "Two flasks".',
  },
  {
    id: 56,
    name: "Fog Bank",
    place: "Shingle Bay",
    cols: 7,
    rows: 8,
    path: [
      [6, 1],
      [0, 1],
      [0, 3],
      [6, 3],
      [6, 5],
      [0, 5],
      [0, 7],
      [5, 7],
    ],
    startMarks: 1820,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
      "tent",
    ],
    waves: ramp(9, {
      v: 11,
      d: 13,
      t: 4,
      truckFrom: 1,
      b: 3,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      p: 4,
      pFrom: 1,
      vs: 1.4,
      e: 3,
      eFrom: 2,
      ds: 1.6,
    }),
    before: [
      {
        who: "narrator",
        text: "Fog comes down over the bay, thick as porridge. The plain grey vans love it. So do the tenders.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "Masts up, tent behind them. If we can't see it, we'll make it glow.",
      },
    ],
    after: [
      {
        who: "sol",
        text: "Every lantern in the harbour has been lit. It looks like Christmas, and it's working.",
      },
    ],
    reward: 'Lore card: "Every lantern".',
  },
  {
    id: 57,
    name: "The Gale",
    place: "Shingle Bay",
    cols: 7,
    rows: 8,
    path: [
      [0, 1],
      [5, 1],
      [5, 3],
      [1, 3],
      [1, 5],
      [6, 5],
      [6, 7],
      [2, 7],
    ],
    startMarks: 1840,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
      "tent",
    ],
    waves: ramp(9, {
      v: 11,
      d: 13,
      t: 4,
      truckFrom: 1,
      b: 3,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      p: 4,
      pFrom: 1,
      vs: 1.4,
      e: 4,
      eFrom: 2,
      ds: 1.6,
    }),
    before: [
      {
        who: "narrator",
        text: "The storm arrives on time. The fishing fleet ties the boats down and comes up to the quay, all of them, in oilskins, holding hands in a very long line.",
      },
      {
        who: "cath",
        expression: "delighted",
        text: "That's the whole harbour. I've never seen so many yellow raincoats in one place.",
      },
    ],
    after: [
      {
        who: "mara",
        text: "They can bring the weather all they like. We've brought a fleet.",
      },
    ],
    reward: 'Lore card: "Yellow raincoats", a whole harbour of them.',
  },
  {
    id: 58,
    name: "Salvage",
    place: "Shingle Bay",
    cols: 7,
    rows: 8,
    path: [
      [0, 0],
      [6, 0],
      [6, 2],
      [0, 2],
      [0, 4],
      [6, 4],
      [6, 6],
      [0, 6],
      [0, 7],
      [6, 7],
    ],
    startMarks: 1860,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
      "tent",
    ],
    waves: ramp(9, {
      v: 11,
      d: 13,
      t: 4,
      truckFrom: 1,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      p: 4,
      pFrom: 1,
      vs: 1.4,
      e: 4,
      eFrom: 1,
      ds: 1.6,
      b: 4,
    }),
    before: [
      {
        who: "narrator",
        text: "When the wind drops, the bay is littered with empty crates stamped WELLNESS. The fishermen collect them for firewood, out of principle.",
      },
      {
        who: "cath",
        expression: "smirk",
        text: "Nobody ever said the corporations couldn't be useful in the end.",
      },
    ],
    after: [
      {
        who: "tomas",
        text: "Best fire the harbour's had in years.",
      },
    ],
    reward: 'Lore card: "Firewood", stamped WELLNESS.',
  },
  {
    id: 59,
    name: "Ship in the Fog",
    place: "Shingle Bay",
    cols: 7,
    rows: 8,
    path: [
      [6, 1],
      [0, 1],
      [0, 3],
      [6, 3],
      [6, 5],
      [0, 5],
      [0, 7],
      [5, 7],
    ],
    startMarks: 1880,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
      "tent",
    ],
    waves: ramp(9, {
      v: 11,
      d: 13,
      t: 4,
      truckFrom: 1,
      bFrom: 0,
      i: 1,
      infFrom: 3,
      p: 4,
      pFrom: 1,
      vs: 1.4,
      e: 4,
      eFrom: 1,
      ds: 1.6,
      b: 4,
    }),
    before: [
      {
        who: "narrator",
        text: "A shape appears in the fog: long, dark, stacked with containers all the colours of a paint catalogue. It sounds one long, low, polite note on its horn.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "That's the Container Ship. It's carrying the whole distribution hub in boxes. If it docks, the harbour's finished.",
      },
    ],
    after: [
      {
        who: "cath",
        expression: "determined",
        text: "We stop it here. Whatever it holds, it isn't going in our quay.",
      },
    ],
    reward: 'Lore card: "One polite note", from a very large horn.',
  },
  {
    id: 60,
    name: "The Container Ship",
    place: "Shingle Bay",
    cols: 7,
    rows: 8,
    path: [
      [0, 1],
      [5, 1],
      [5, 3],
      [1, 3],
      [1, 5],
      [6, 5],
      [6, 7],
      [2, 7],
    ],
    startMarks: 2000,
    goodwill: 10,
    towers: [
      "hedgerow",
      "scarecrow",
      "beehive",
      "stall",
      "pond",
      "barn",
      "silo",
      "mast",
      "tent",
    ],
    waves: [
      ...ramp(6, {
        v: 11,
        d: 13,
        t: 4,
        truckFrom: 1,
        bFrom: 0,
        i: 1,
        infFrom: 3,
        p: 3,
        pFrom: 1,
        vs: 1.4,
        ds: 1.5,
        e: 4,
        eFrom: 0,
        b: 4,
      }),
      [
        ship(0),
        tender(4, 2, 6),
        phantom(4, 2, 6),
        bulldozer(4, 3, 8),
        van(12, 1.2, 8),
        drone(14, 0.55, 10),
      ],
    ],
    before: [
      {
        who: "narrator",
        text: "The Container Ship rounds the harbour wall at dawn, and it is even bigger than the fog made it. Its horn plays the first bars of a jingle.",
      },
      {
        who: "cath",
        expression: "determined",
        text: "It's armoured and slow, and it splits into tenders when it sinks. Silos, tent, pie, and a great deal of patience.",
      },
      {
        who: "tomas",
        text: "My grandfather's boat is still tied up behind the wall. I'd like it to stay there.",
      },
    ],
    after: [
      {
        who: "narrator",
        text: "The ship lists, groans, and sits down gently in the shallows. Its crates float free, and the fleet gets to work on them.",
      },
      {
        who: "cath",
        expression: "delighted",
        text: "The harbour is ours, and every yellow raincoat has earned a tea.",
      },
      {
        who: "cath",
        expression: "worried",
        text: "The Rift next. Hollowell and Candor have fallen out with each other, which should be good news. Somehow it isn't.",
      },
    ],
    reward:
      'Act 6 complete. Lore card: "Firewood and rope", the harbour\'s thanks.',
  },
];

export function levelById(id: number): Level | undefined {
  return LEVELS.find((l) => l.id === id);
}
