// Hedgerow's levels. H1 ships the first three of act 1, Brindle Hills (docs/design/hedgerow.md). Story
// follows SPEC 3.2's voice: short, specific, dry, warm. Later acts append to LEVELS.

import type { Level, WaveGroup } from './engine'

const van = (count: number, gap: number, delay = 0): WaveGroup => ({ enemy: 'van', count, gap, delay })
const boss = (delay = 0): WaveGroup => ({ enemy: 'boss', count: 1, gap: 1, delay })
const drone = (count: number, gap: number, delay = 0): WaveGroup => ({ enemy: 'drone', count, gap, delay })

export const LEVELS: Level[] = [
  {
    id: 1,
    name: "Mara's Field",
    place: 'Brindle Hills',
    cols: 6,
    rows: 7,
    path: [[0, 1], [4, 1], [4, 3], [1, 3], [1, 5], [5, 5]],
    startMarks: 210,
    goodwill: 10,
    towers: ['hedgerow', 'scarecrow'],
    waves: [
      [van(3, 3)],
      [van(4, 2.6)],
      [van(4, 2.4), drone(2, 1.5, 6)],
      [van(5, 2.2), drone(3, 1.4, 5)],
      [van(6, 2), drone(4, 1.2, 4)],
    ],
    before: [
      { who: 'narrator', text: 'Brindle Hills, a Tuesday. Mara is halfway through a cheese sandwich when something hums overhead.' },
      { who: 'mara', text: "There's a drone in my beans, Cath. It's taking photographs. Of my beans." },
      { who: 'cath', expression: 'determined', text: "Then it's a survey. First the photographs, then the offer, then the bulldozer. I've seen the order." },
      { who: 'cath', expression: 'wink', text: "Good news: you've got a hedge, a scarecrow and me. Let's put them where the lane bends." },
    ],
    after: [
      { who: 'mara', text: "Well. That's the first van I've ever seen turn round on its own." },
      { who: 'cath', expression: 'smirk', text: "It won't be the last one that comes. But now they know what your beans are made of." },
    ],
    reward: 'Lore card: "Mara\'s ledger", forty years of bean prices, all of them fair.',
  },
  {
    id: 2,
    name: 'The Long Lane',
    place: 'Brindle Hills',
    cols: 6,
    rows: 8,
    path: [[5, 0], [1, 0], [1, 2], [4, 2], [4, 4], [0, 4], [0, 6], [5, 6]],
    startMarks: 190,
    goodwill: 10,
    towers: ['hedgerow', 'scarecrow'],
    waves: [
      [van(4, 2.8)],
      [drone(4, 1.4), van(2, 2.6, 3)],
      [van(5, 2.2), drone(3, 1.2, 4)],
      [van(4, 2), drone(6, 1.1, 3)],
      [van(6, 1.9), drone(5, 1.1, 4)],
      [van(7, 1.7), drone(6, 1, 3)],
    ],
    before: [
      { who: 'narrator', text: 'Word travels fast in Brindle Hills. By breakfast, four farms know about the drone.' },
      { who: 'bea', expression: 'delighted', text: "I drew the van! It has a smiley face on it. Why do the mean ones always have smiley faces?" },
      { who: 'cath', expression: 'smirk', text: "Because a frown wouldn't test well with customers, sweetheart." },
      { who: 'cath', expression: 'determined', text: "They're coming down the long lane this time. Plenty of room for hedges. Bea, you keep score." },
    ],
    after: [
      { who: 'bea', expression: 'delighted', text: 'Twenty-seven vans! I counted. Can I draw a medal for the hedge?' },
      { who: 'cath', expression: 'wink', text: "Draw one for everyone. Hedges first." },
    ],
    reward: 'Scarecrow skin: "Bea\'s Sunday best", a hat and a very small bow tie.',
  },
  {
    id: 3,
    name: 'The Acquisition Van',
    place: 'Brindle Hills',
    cols: 6,
    rows: 8,
    path: [[0, 1], [5, 1], [5, 3], [0, 3], [0, 5], [5, 5]],
    startMarks: 260,
    goodwill: 10,
    towers: ['hedgerow', 'scarecrow'],
    waves: [
      [van(5, 2.4)],
      [drone(6, 1.2), van(3, 2.4, 2)],
      [van(6, 2), drone(5, 1.1, 3)],
      [van(7, 1.8), drone(6, 1, 3)],
      [van(8, 1.6), drone(7, 0.9, 2)],
      [van(9, 1.5), drone(8, 0.9, 2)],
      [van(11, 1.3), drone(9, 0.8, 2)],
    ],
    before: [
      { who: 'narrator', text: 'A very clean white van parks at the edge of the hills. Nobody sees anyone get out. That is the alarming part.' },
      { who: 'tomas', text: "It's an acquisition van. There's an offer letter on every windscreen in the valley. Nice paper, too." },
      { who: 'cath', expression: 'determined', text: "Everything they send is in the same font. That's how you know it's one company with two names." },
      { who: 'cath', expression: 'wink', text: "Right. Vans first, drones after, and nobody sells a thing today." },
    ],
    after: [
      { who: 'tomas', text: "They've stopped. Do you think that's the end of it?" },
      { who: 'cath', expression: 'worried', text: "No. They've gone to get a bigger van." },
    ],
    reward: 'Lore card: "The offer letter", 400 words that never once say the word "no".',
  },
  {
    id: 4,
    name: "Bea's Beehive",
    place: 'Brindle Hills',
    cols: 6,
    rows: 8,
    path: [[0, 0], [3, 0], [3, 2], [0, 2], [0, 4], [4, 4], [4, 6], [1, 6], [1, 7], [5, 7]],
    startMarks: 280,
    goodwill: 10,
    towers: ['hedgerow', 'scarecrow', 'beehive'],
    waves: [
      [van(5, 2.2)],
      [drone(6, 1.1), van(4, 2.2, 2)],
      [van(7, 1.9), drone(5, 1.1, 3)],
      [van(8, 1.7), drone(6, 1, 3)],
      [van(9, 1.5), drone(8, 0.9, 2)],
      [van(10, 1.4), drone(9, 0.8, 2)],
    ],
    before: [
      { who: 'narrator', text: "Bea has been keeping bees behind the barn for a fortnight. Nobody was told. The bees weren't told either." },
      { who: 'bea', expression: 'delighted', text: "They like the vans! They follow them! Is that bad?" },
      { who: 'cath', expression: 'wink', text: "It is the best thing that's happened all week. Bea, we're going to need a lot more hives." },
      { who: 'cath', expression: 'determined', text: "New tool: the Beehive. It stings everything near its target, so put it where the queue bunches up." },
    ],
    after: [
      { who: 'bea', expression: 'delighted', text: "I named them all. This one is Gerald." },
      { who: 'cath', expression: 'smirk', text: "Gerald did wonderful work." },
    ],
    reward: 'Unlocked: the Beehive (sting a whole queue at once). Lore card: "Gerald".',
  },
  {
    id: 5,
    name: 'Price War',
    place: 'Brindle Hills',
    cols: 6,
    rows: 8,
    path: [[5, 0], [5, 2], [0, 2], [0, 4], [5, 4], [5, 6], [0, 6], [0, 7], [5, 7]],
    startMarks: 300,
    goodwill: 10,
    towers: ['hedgerow', 'scarecrow', 'beehive'],
    waves: [
      [drone(8, 0.9)],
      [van(6, 1.8), drone(6, 1, 2)],
      [drone(10, 0.7), van(6, 1.7, 3)],
      [van(9, 1.5), drone(9, 0.8, 2)],
      [drone(14, 0.6), van(8, 1.5, 3)],
      [van(11, 1.3), drone(12, 0.7, 2)],
      [van(12, 1.2), drone(16, 0.55, 2)],
    ],
    before: [
      { who: 'tomas', text: "They've cut every price in the valley by half. Even the eggs. Who sells eggs at half price? Nobody. It's a trap." },
      { who: 'cath', expression: 'determined', text: "It's a price war. They lose money until you close, then the prices come back up, with interest." },
      { who: 'cath', expression: 'smirk', text: "Everyone will want the cheap eggs. Our job is to make the cheap eggs hard to get to." },
    ],
    after: [
      { who: 'tomas', text: "Well. I'm keeping my prices. Slightly higher than theirs. Slightly better eggs." },
      { who: 'cath', expression: 'delighted', text: "That's the whole business plan, Tomas. Put it on a sign." },
    ],
    reward: 'Lore card: "Tomas\'s egg sign", hand-painted, very slightly crooked.',
  },
  {
    id: 6,
    name: 'The Long Weekend',
    place: 'Brindle Hills',
    cols: 6,
    rows: 8,
    path: [[0, 0], [5, 0], [5, 2], [1, 2], [1, 4], [4, 4], [4, 6], [0, 6], [0, 7], [5, 7]],
    startMarks: 320,
    goodwill: 10,
    towers: ['hedgerow', 'scarecrow', 'beehive'],
    waves: [
      [van(6, 2)],
      [van(6, 1.8), drone(8, 0.9, 2)],
      [van(9, 1.5), drone(8, 0.8, 2)],
      [van(10, 1.4), drone(10, 0.75, 2)],
      [van(12, 1.2), drone(10, 0.7, 2)],
      [van(13, 1.1), drone(12, 0.65, 2)],
      [van(15, 1), drone(14, 0.6, 2)],
      [van(16, 0.95), drone(16, 0.55, 2)],
    ],
    before: [
      { who: 'narrator', text: 'Saturday. The corporations do not believe in weekends, only in overtime.' },
      { who: 'mara', text: "Forty vans, Cath. I counted them. They're coming in shifts." },
      { who: 'cath', expression: 'worried', text: "That's the biggest push yet. They've stopped sending letters and started sending people." },
      { who: 'cath', expression: 'wink', text: "But we have a lane, a hedge and Gerald. I like our odds." },
    ],
    after: [
      { who: 'mara', text: 'Sunday tea, then?' },
      { who: 'cath', expression: 'smirk', text: "Sunday tea. And someone go and check on the acquisition van. It's been very quiet over there." },
    ],
    reward: 'Lore card: "Shift rota", a list of vans with a very tired-looking note at the bottom.',
  },
  {
    id: 7,
    name: 'Crooked Fences',
    place: 'Brindle Hills',
    cols: 6,
    rows: 8,
    path: [[0, 7], [0, 5], [3, 5], [3, 3], [0, 3], [0, 1], [5, 1], [5, 7]],
    startMarks: 400,
    goodwill: 10,
    towers: ['hedgerow', 'scarecrow', 'beehive'],
    waves: [
      [van(7, 1.8)],
      [van(8, 1.6), drone(8, 0.8, 2)],
      [van(10, 1.4), drone(10, 0.7, 2)],
      [van(11, 1.3), drone(12, 0.65, 2)],
      [van(13, 1.2), drone(12, 0.6, 2)],
      [van(14, 1.1), drone(14, 0.55, 2)],
    ],
    before: [
      { who: 'narrator', text: "Overnight, someone moves Mara's fence posts four feet to the left. It is technically legal. That is the worst part." },
      { who: 'mara', text: 'Their surveyor says my field is smaller than I thought. My field has been this size since 1974.' },
      { who: 'cath', expression: 'determined', text: "Then we hold every inch of it, including the inches they've decided don't exist." },
    ],
    after: [
      { who: 'mara', text: 'I moved the fence back. It is now six inches further left than it was. I win.' },
      { who: 'cath', expression: 'wink', text: "That's the spirit. Slightly petty and completely correct." },
    ],
    reward: 'Lore card: "Mara\'s tape measure", 30 metres of proof.',
  },
  {
    id: 8,
    name: 'The Survey',
    place: 'Brindle Hills',
    cols: 6,
    rows: 8,
    path: [[0, 0], [2, 0], [2, 2], [5, 2], [5, 4], [2, 4], [2, 6], [5, 6], [5, 7]],
    startMarks: 440,
    goodwill: 10,
    towers: ['hedgerow', 'scarecrow', 'beehive'],
    waves: [
      [drone(10, 0.8)],
      [van(8, 1.6), drone(10, 0.7, 2)],
      [van(10, 1.4), drone(12, 0.65, 2)],
      [drone(18, 0.5), van(9, 1.4, 3)],
      [van(13, 1.2), drone(14, 0.6, 2)],
      [van(15, 1.1), drone(16, 0.55, 2)],
      [van(16, 1), drone(18, 0.5, 2)],
    ],
    before: [
      { who: 'narrator', text: 'Forty drones, one clipboard. A young man in a hi-vis vest stands at the gate and says he is "just here to measure".' },
      { who: 'bea', expression: 'worried', text: "He's measuring the beehives. Why is he measuring the beehives?" },
      { who: 'cath', expression: 'determined', text: "Because a hive is worth money, sweetheart. And they'd like to own it." },
      { who: 'cath', expression: 'smirk', text: "Nobody owns Gerald. Gerald is a free bee." },
    ],
    after: [
      { who: 'bea', expression: 'delighted', text: 'The man in the vest fell in the pond. Was that us?' },
      { who: 'cath', expression: 'wink', text: "Officially, no." },
    ],
    reward: 'Lore card: "The clipboard", left behind, with one very honest line: "Nobody seems to mind."',
  },
  {
    id: 9,
    name: 'Night Shift',
    place: 'Brindle Hills',
    cols: 6,
    rows: 8,
    path: [[5, 0], [0, 0], [0, 2], [4, 2], [4, 4], [1, 4], [1, 6], [5, 6], [5, 7]],
    startMarks: 460,
    goodwill: 10,
    towers: ['hedgerow', 'scarecrow', 'beehive'],
    waves: [
      [van(8, 1.5)],
      [van(9, 1.4), drone(12, 0.65, 2)],
      [van(12, 1.2), drone(12, 0.6, 2)],
      [van(13, 1.1), drone(15, 0.55, 2)],
      [van(15, 1), drone(16, 0.5, 2)],
      [van(17, 0.95), drone(18, 0.5, 2)],
      [van(18, 0.9), drone(20, 0.45, 2)],
    ],
    before: [
      { who: 'narrator', text: 'At two in the morning the vans come with their lights off. The drones do not have lights to turn off, which is somehow worse.' },
      { who: 'cath', expression: 'determined', text: "They've stopped pretending it's polite. That means they know the acquisition van is nearly ready." },
      { who: 'tomas', text: 'Should I make tea?' },
      { who: 'cath', expression: 'smirk', text: 'Make a lot of tea, Tomas. It is going to be that kind of night.' },
    ],
    after: [
      { who: 'tomas', text: 'The tea was excellent. The vans were not.' },
      { who: 'cath', expression: 'worried', text: "Something big is coming up the road. I can feel it in the fence posts." },
    ],
    reward: 'Lore card: "Tomas\'s flask", still warm.',
  },
  {
    id: 10,
    name: 'The Acquisition',
    place: 'Brindle Hills',
    cols: 6,
    rows: 8,
    path: [[0, 0], [5, 0], [5, 2], [0, 2], [0, 4], [5, 4], [5, 6], [0, 6], [0, 7], [5, 7]],
    startMarks: 380,
    goodwill: 10,
    towers: ['hedgerow', 'scarecrow', 'beehive'],
    waves: [
      [van(8, 1.5)],
      [van(10, 1.3), drone(12, 0.6, 2)],
      [van(12, 1.2), drone(14, 0.55, 2)],
      [van(14, 1.1), drone(16, 0.5, 2)],
      [van(16, 1), drone(18, 0.5, 2)],
      [boss(0), van(12, 1.2, 6), drone(16, 0.55, 8)],
    ],
    before: [
      { who: 'narrator', text: 'The Acquisition Van is the size of a barn. It has a slogan on the side: "WE\'RE HERE FOR YOU." It has a smile, too. Nobody asked for the smile.' },
      { who: 'mara', text: "Cath, that isn't a van. That's a lawyer with wheels." },
      { who: 'cath', expression: 'determined', text: "It's what they send when they've run out of letters. It's slow, it's enormous and it's utterly convinced it's already won." },
      { who: 'cath', expression: 'wink', text: "Every hedge, every scarecrow, every hive, Gerald included. Let's show it what Brindle Hills thinks of an offer." },
    ],
    after: [
      { who: 'narrator', text: 'The Acquisition Van sits in the lane, stopped. A single, very small turnip rolls off its roof.' },
      { who: 'mara', text: "Forty years I've farmed this valley. I never thought I'd see the day a van gave up." },
      { who: 'cath', expression: 'smirk', text: "It didn't give up, Mara. It went to get advice. Highmoor is next, and their advice comes with a price tag." },
    ],
    reward: 'Act 1 complete. Lore card: "The Van\'s manifesto", 90 pages, not one of them about farming.',
  },
]

export function levelById(id: number): Level | undefined {
  return LEVELS.find((l) => l.id === id)
}
